receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  attributes:
    actions:
      - key: "service.name"
        action: "insert"
        from_attribute: "service.name"
        value: "quote_api_service"

exporters:
  logging:
    verbosity: detailed
  
  otlp:
    endpoint: lgtm:3200
    tls:
      insecure: true
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  prometheus:
    endpoint: "0.0.0.0:8888"
    namespace: "otel"
    const_labels:
      label1: value1
    send_timestamps: true
    metric_relabel_configs:
      - action: labeldrop
        regex: ^(target_info|target_info.*)$

  loki:
    endpoint: "http://lgtm:3100/loki/api/v1/push"
    labels:
      resource:
        service.name: "service_name"
    attributes:
      service.name: "service_name"
    tenant_id: "quote_api_service"
    default_labels_enabled:
      container: true
      namespace: true
      pod: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [prometheus, otlp]
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [loki] 